server:
  port: 8001
#  ssl:
#    key-store: server.keystore
#    key-alias: tomcat
#    enabled: true
#    key-store-password: 123456
#    key-store-type: JKS
spring:
  application:
    name: lziot-eureka
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/