server:
  port: 9001
  ssl:
#    key-store: classpath:cert/demo/tomcat.keystore
##    key-store: classpath:cert/demo/ca.jks
#    key-store-password: 123456
#    trust-store: classpath:cert/demo/tomcat.keystore
##    trust-store: classpath:cert/demo/outgoing.CertwithKey.pkcs12
#    trust-store-password: 123456
#    client-auth: need
    key-store: classpath:cert/bak/tomcat.keystore
    key-store-password: bonc123456
    trust-store: classpath:cert/bak/tomcat.keystore
    trust-store-password: bonc123456
    client-auth: need