server:
  port: 8001
#spring:
#  application:
#    name: eureka
#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: false
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl: